module.exports = {
    CLASS: 'class',
    INTERFACE: 'interface',
    ENUM: 'enum',
    PROPERTY: 'property',
    GETTER: 'getter',
    SETTER: 'setter',
    INITIALIZER: 'initializer',
    METHOD: 'method',
    CONSTRUCTOR: 'constructor',
    STATIC_CONSTRUCTOR: 'static_constructor',
    VARIABLE: 'variable',
    TRIGGER: 'trigger',
    COMMENT: 'comment',
    BLOCK_COMMENT: 'block_comment',
    DATATYPE: 'datatype',
    ANNOTATION: 'annotation',
    SOQL: 'soql',
    SOQL_FIELD: 'soql_field'
};