export const MetadataTypes: MetadataTypesDef = {
  ACCOUNT_RELATIONSHIP_SHARE_RULE: 'AccountRelationshipShareRule',
  ACTION_LINK_GROUP_TEMPLATE: 'ActionLinkGroupTemplate',
  ACTION_OVERRIDE: 'ActionOverride',
  ACTION_PLAN_TEMPLATE: 'ActionPlanTemplate',
  AI_APPLICATION: 'AIApplication',
  AI_APPLICATION_CONFIG: 'AIApplicationConfig',
  ANALITYC_SNAPSHOT: 'AnalyticSnapshot',
  ANIMATION_RULE: 'AnimationRule',
  APEX_CLASS: 'ApexClass',
  APEX_COMPONENT: 'ApexComponent',
  APEX_EMAIL_NOTIFICATIONS: 'ApexEmailNotifications',
  APEX_PAGE: 'ApexPage',
  APEX_TEST_SUITE: 'ApexTestSuite',
  APEX_TRIGGER: 'ApexTrigger',
  APPOINTMENT_ASSIGNMENT_POLICY: 'AppointmentAssignmentPolicy',
  APPOINTMENT_SCHEDULING_POLICY: 'AppointmentSchedulingPolicy',
  APPROVAL_PROCESSES: 'ApprovalProcess',
  ARTICLE_TYPE: 'ArticleType',
  ASSIGNMENT_RULE: 'AssignmentRule',
  ASSIGNMENT_RULES: 'AssignmentRules',
  AUDIENCE: 'Audience',
  AURA_DEFINITION_BUNDLE: 'AuraDefinitionBundle',
  AUTH_PROVIDER: 'AuthProvider',
  AUTORESPONSE_RULE: 'AutoResponseRule',
  AUTORESPONSE_RULES: 'AutoResponseRules',
  BATCH_CALC_JOB_DEFINITION: 'BatchCalcJobDefinition',
  BATCH_PROCESS_JOB_DEFINITION: 'BatchProcessJobDefinition',
  BLACKLISTED_CONSUMER: 'BlacklistedConsumer',
  BOT: 'Bot',
  BOT_VERSION: 'BotVersion',
  BRANDING_SET: 'BrandingSet',
  BRIEFCASE_DEFINITION: 'BriefcaseDefinition',
  BUSINESS_PROCESS: 'BusinessProcess',
  BUSINESS_PROCESS_GROUP: 'BusinessProcessGroup',
  CALL_COACHING_MEDIA_PROVIDER: 'CallCoachingMediaProvider',
  CAMPAIGN_INFLUENCE_MODEL: 'campaignInfluenceModel',
  CARE_PROVIDER_SEARCH_CONFIG: 'CareProviderSearchConfig',
  CARE_SYSTEM_FIELD_MAPPING: 'CareSystemFieldMapping',
  CASE_SUBJECT_PARTICLE: 'CaseSubjectParticle',
  CERTIFICATE: 'Certificate',
  CHATTER_EXTENSION: 'ChatterExtension',
  CLEAN_DATA_SERVICE: 'CleanDataService',
  CMS_CONNECT_SOURCE: 'CMSConnectSource',
  COMMUNITY: 'Community',
  COMMUNITY_TEMPLATE_DEFINITION: 'CommunityTemplateDefinition',
  COMMUNITY_THEME_DEFINITION: 'CommunityThemeDefinition',
  COMPACT_LAYOUT: 'CompactLayout',
  CONNECTED_APP: 'ConnectedApp',
  CONTENT_ASSET: 'ContentAsset',
  CORS_WHITELIST_ORIGIN: 'CorsWhitelistOrigin',
  CSP_TRUSTED_SITE: 'CspTrustedSite',
  CUSTOM_APPLICATION: 'CustomApplication',
  CUSTOM_APP_COMPONENT: 'CustomApplicationComponent',
  CUSTOM_FEED_FILTER: 'CustomFeedFilter',
  CUSTOM_FIELD: 'CustomField',
  CUSTOM_HELP_MENU_SECTION: 'CustomHelpMenuSection',
  CUSTOM_LABEL: 'CustomLabel',
  CUSTOM_LABELS: 'CustomLabels',
  CUSTOM_METADATA: 'CustomMetadata',
  CUSTOM_NOTIFICATION_TYPE: 'CustomNotificationType',
  CUSTOM_OBJECT: 'CustomObject',
  CUSTOM_OBJECT_TRANSLATIONS: 'CustomObjectTranslation',
  CUSTOM_PAGE_WEB_LINK: 'CustomPageWebLink',
  CUSTOM_PERMISSION: 'CustomPermission',
  CUSTOM_SITE: 'CustomSite',
  CUSTOM_TAB: 'CustomTab',
  DASHBOARD: 'Dashboard',
  DATA_CATEGORY_GROUP: 'DataCategoryGroup',
  DATA_PACKAGE_KIT_OBJECT: 'DataPackageKitObject',
  DATA_PACKAGE_KIT_DEFINITION: 'DataPackageKitDefinition',
  DATA_SOURCE: 'DataSource',
  DATA_SOURCE_OBJECT: 'DataSourceObject',
  DATA_STREAM_DEFINITION: 'DataStreamDefinition',
  DECISION_TABLE: 'DecisionTable',
  DECISION_TABLE_DATASET_LINK: 'DecisionTableDatasetLink',
  DELEGATE_GROUP: 'DelegateGroup',
  DISCOVERY_AI_MODEL: 'DiscoveryAIModel',
  DISCOVERY_GOAL: 'DiscoveryGoal',
  DOCUMENT: 'Document',
  DUPLICATE_RULE: 'DuplicateRule',
  ECLAIR_GEO_DATA: 'EclairGeoData',
  EMAIL_SERVICES_FUNCTION: 'EmailServicesFunction',
  EMAIL_TEMPLATE: 'EmailTemplate',
  EMBEDDED_SERVICE_BRANDING: 'EmbeddedServiceBranding',
  EMBEDDED_SERVICE_CONFIG: 'EmbeddedServiceConfig',
  EMBEDDED_SERVICE_FIELD_SERVICE: 'EmbeddedServiceFieldService',
  EMBEDDED_SERVICE_FLOW_CONFIG: 'EmbeddedServiceFlowConfig',
  EMBEDDED_SERVICE_LIVE_AGENT: 'EmbeddedServiceLiveAgent',
  EMBEDDED_SERVICE_MENU_SETTINGS: 'EmbeddedServiceMenuSettings',
  ENTITLEMENT_PROCESS: 'EntitlementProcess',
  ENTITLEMENT_TEMPLATE: 'EntitlementTemplate',
  EXTERNAL_AI_MODEL: 'ExternalAIModel',
  ESCALATION_RULE: 'EscalationRule',
  ESCALATION_RULES: 'EscalationRules',
  EVENT_DELIVERY: 'EventDelivery',
  EVENT_SUBSCRIPTION: 'EventSubscription',
  EXPERIENCE_BUNDLE: 'ExperienceBundle',
  EXTERNAL_DATA_CONNECTOR: 'ExternalDataConnector',
  EXTERNAL_DATA_SOURCE: 'ExternalDataSource',
  EXTERNAL_SERVICE_REGISTRATION: 'ExternalServiceRegistration',
  FEATURE_PARAMETER_BOOLEAN: 'FeatureParameterBoolean',
  FEATURE_PARAMETER_DATE: 'FeatureParameterDate',
  FEATURE_PARAMETER_INTEGER: 'FeatureParameterInteger',
  FIELD_RESTRICTION_RULE: 'FieldRestrictionRule',
  FIELD_SET: 'FieldSet',
  FIELD_SRC_TRGT_RELATIONSHIP: 'FieldSrcTrgtRelationship',
  FLEXI_PAGE: 'FlexiPage',
  FLOW: 'Flow',
  FLOW_CATEGORY: 'FlowCategory',
  FLOW_DEFINITION: 'FlowDefinition',
  FOLDER: 'Folder',
  FORECASTING_SOURCE_DEFFINITION: 'ForecastingSourceDefinition',
  FORECASTING_TYPE: 'ForecastingType',
  FORECASTING_TYPE_SOURCE: 'ForecastingTypeSource',
  FUNCTION_REFERENCE: 'FunctionReference',
  GATEWAY_PROVIDER_PAYMENT_METHOD_TYPE: 'GatewayProviderPaymentMethodType',
  GLOBAL_PICKLIST: 'GlobalPicklist',
  GLOBAL_VALUE_SET: 'GlobalValueSet',
  GLOBAL_VALUE_SET_TRANSLATION: 'GlobalValueSetTranslation',
  GROUP: 'Group',
  HISTORY_RETENTION_POLICY: 'HistoryRetentionPolicy',
  HOME_COMPONENT: 'HomePageComponent',
  HOME_PAGE_LAYOUT: 'HomePageLayout',
  INBOUND_CERTIFICATE: 'InboundCertificate',
  INBOUND_NETWORK_CONNECTION: 'InboundNetworkConnection',
  INDEX: 'Index',
  INSTALLED_PACKAGE: 'InstalledPackage',
  IP_ADDRESS_RANGE: 'IPAddressRange',
  KEYWORD_LIST: 'KeywordList',
  LAYOUT: 'Layout',
  LETTERHEAD: 'Letterhead',
  LIGHTNING_BOLT: 'LightningBolt',
  LIGHTNING_COMPONENT_BUNDLE: 'LightningComponentBundle',
  LIGHTNING_EXPERIENCE_THEME: 'LightningExperienceTheme',
  LIGHTNING_MESSAGE_CHANNEL: 'LightningMessageChannel',
  LIGHTNING_ONBOARDING_CONFIG: 'LightningOnboardingConfig',
  LISTVIEW: 'ListView',
  LIVE_CHAT_AGENT_CONFIG: 'LiveChatAgentConfig',
  LIVE_CHAT_BUTTON: 'LiveChatButton',
  LIVE_CHAT_DEPLOYMENT: 'LiveChatDeployment',
  LIVE_CHAT_SENSITIVE_DATA_RULE: 'LiveChatSensitiveDataRule',
  MANAGED_CONTENT_TYPE: 'ManagedContentType',
  MANAGED_TOPICS: 'ManagedTopics',
  MATCHING_RULE: 'MatchingRule',
  MATCHING_RULES: 'MatchingRules',
  MILESTONE_TYPE: 'MilestoneType',
  ML_PREDICTION_DEFINITION: 'MLPredictionDefinition',
  ML_DATA_DEFINITION: 'MLDataDefinition',
  ML_DOMAIN: 'MlDomain',
  MKT_CALC_INSIGHT_OBJECT_DEF: 'MktCalcInsightObjectDef',
  MKT_DATA_TRAN_OBJECT: 'MktDataTranObject',
  MOBILE_APPLICATION_DETAIL: 'MobileApplicationDetail',
  MODERATION_RULE: 'ModerationRule',
  MUTING_PERMISSION_SET: 'MutingPermissionSet',
  MY_DOMAIN_DISCOVERABLE_LOGIN: 'MyDomainDiscoverableLogin',
  NAMED_CREDENTIAL: 'NamedCredential',
  NAMED_FILTER: 'NamedFilter',
  NAVIGATION_MENU: 'NavigationMenu',
  NETWORK: 'Network',
  NETWORK_BRANDING: 'NetworkBranding',
  NOTIFICATION_TYPE_CONFIG: 'NotificationTypeConfig',
  OAUTH_CUSTOM_SCOPE: 'OauthCustomScope',
  OBJECT_SOURCE_TARGET_MAP: 'ObjectSourceTargetMap',
  OCR_SAMPLE_DOCUMENT: 'OcrSampleDocument',
  OCR_TEMPLATE: 'OcrTemplate',
  OUTBOUND_NETWORK_CONNECTION: 'OutboundNetworkConnection',
  PACKAGE: 'Package',
  PATH_ASSISTANT: 'PathAssistant',
  PAYMENT_GATEWAY_PROVIDER: 'PaymentGatewayProvider',
  PERMISSION_SET: 'PermissionSet',
  PERMISSION_SET_GROUP: 'PermissionSetGroup',
  PLATFORM_CACHE_PARTITION: 'PlatformCachePartition',
  PLATFORM_EVENT_CHANNEL: 'PlatformEventChannel',
  PLATFORM_EVENT_CHANNEL_MEMBER: 'PlatformEventChannelMember',
  PLATFORM_EVENT_SUBSCRIBER_CONFIG: 'PlatformEventSubscriberConfig',
  PORTAL: 'Portal',
  POST_TEMPLATE: 'PostTemplate',
  PRESENCE_DECLINE_REASON: 'PresenceDeclineReason',
  PRESENCE_USER_CONFIG: 'PresenceUserConfig',
  PROFILE: 'Profile',
  PROFILE_PASSWORD_POLICY: 'ProfilePasswordPolicy',
  PROFILE_SEARCH_LAYOUTS: 'ProfileSearchLayouts',
  PROFILE_SESSION_SETTING: 'ProfileSessionSetting',
  PROMPT: 'Prompt',
  QUEUE: 'Queue',
  QUEUE_ROUTING_CONFIG: 'QueueRoutingConfig',
  QUICK_ACTION: 'QuickAction',
  RECOMMENDATION_STRATEGY: 'RecommendationStrategy',
  RECORD_ACTION_DEPLOYMENT: 'RecordActionDeployment',
  RECORD_TYPE: 'RecordType',
  REDIRECT_WHITELIST_URL: 'RedirectWhitelistUrl',
  REMOTE_SITE_SETTING: 'RemoteSiteSetting',
  REPORT: 'Report',
  REPORT_TYPE: 'ReportType',
  ROLE: 'Role',
  SALES_WORK_QUEUE_SETTINGS: 'SalesWorkQueueSettings',
  SAML_SSO_CONFIG: 'SamlSsoConfig',
  S_CONTROL: 'Scontrol',
  SEARCH_LAYOUTS: 'SearchLayouts',
  SERVICE_AI_SETUP_DEFINITION: 'ServiceAISetupDefinition',
  SERVICE_AI_SETUP_FIELD: 'ServiceAISetupField',
  SERVICE_CHANNEL: 'ServiceChannel',
  SERVICE_PRESENCE_STATUS: 'ServicePresenceStatus',
  SHARED_TO: 'SharedTo',
  SHARING_REASON: 'SharingReason',
  SHARING_RECALCULATION: 'SharingRecalculation',
  SHARING_RULES: 'SharingRules',
  SHARING_OWNER_RULE: 'SharingOwnerRule',
  SHARING_CRITERIA_RULE: 'SharingCriteriaRule',
  SHARING_TERRITORY_RULE: 'SharingTerritoryRule',
  SHARING_GUEST_RULE: 'SharingGuestRule',
  SHARING_SET: 'SharingSet',
  SITE_DOT_COM: 'SiteDotCom',
  SKILL: 'Skill',
  STANDARD_VALUE_SET: 'StandardValueSet',
  STANDARD_VALUE_SET_TRANSLATION: 'StandardValueSetTranslation',
  STATIC_RESOURCE: 'StaticResource',
  SYNONYM_DICTIONARY: 'SynonymDictionary',
  TERRITORY: 'Territory',
  TERRITORY_2: 'Territory2',
  TERRITORY_2_MODEL: 'Territory2Model',
  TERRITORY_2_RULE: 'Territory2Rule',
  TERRITORY_2_TYPE: 'Territory2Type',
  TIME_SHEET_TEMPLATE: 'TimeSheetTemplate',
  TOPICS_FOR_OBJECT: 'TopicsForObjects',
  TRANSACTION_SECURITY_POLICY: 'TransactionSecurityPolicy',
  TRANSLATIONS: 'Translations',
  USER_AUTH_CERTIFICATE: 'UserAuthCertificate',
  USER_CRITERIA: 'UserCriteria',
  USER_PROVISIONING_CONFIG: 'UserProvisioningConfig',
  VALIDATION_RULE: 'ValidationRule',
  WAVE_APPLICATION: 'WaveApplication',
  WAVE_DASHBOARD: 'WaveDashboard',
  WAVE_DATA_FLOW: 'WaveDataflow',
  WAVE_DATASET: 'WaveDataset',
  WAVE_LENS: 'WaveLens',
  WAVE_RECIPE: 'WaveRecipe',
  WAVE_TEMPLATE_BUNDLE: 'WaveTemplateBundle',
  WAVE_XMD: 'WaveXmd',
  WEBLINK: 'WebLink',
  WEB_STORE_TEMPLATE: 'WebStoreTemplate',
  WORKFLOW: 'Workflow',
  WORKFLOW_ALERT: 'WorkflowAlert',
  WORKFLOW_FIELD_UPDATE: 'WorkflowFieldUpdate',
  WORKFLOW_RULE: 'WorkflowRule',
  WORKFLOW_TASK: 'WorkflowTask',
  WORKFLOW_SEND: 'WorkflowSend',
  WORKFLOW_OUTBOUND_MESSAGE: 'WorkflowOutboundMessage',
  WORKFLOW_KNOWLEDGE_PUBLISH: 'WorkflowKnowledgePublish',
  WORK_SKILL_ROUTING: 'WorkSkillRouting',
};

export interface MetadataTypesDef {
  ACCOUNT_RELATIONSHIP_SHARE_RULE: string;
  ACTION_LINK_GROUP_TEMPLATE: string;
  ACTION_OVERRIDE: string;
  ACTION_PLAN_TEMPLATE: string;
  AI_APPLICATION: string;
  AI_APPLICATION_CONFIG: string;
  ANALITYC_SNAPSHOT: string;
  ANIMATION_RULE: string;
  APEX_CLASS: string;
  APEX_COMPONENT: string;
  APEX_EMAIL_NOTIFICATIONS: string;
  APEX_PAGE: string;
  APEX_TEST_SUITE: string;
  APEX_TRIGGER: string;
  APPOINTMENT_ASSIGNMENT_POLICY: string;
  APPOINTMENT_SCHEDULING_POLICY: string;
  APPROVAL_PROCESSES: string;
  ARTICLE_TYPE: string;
  ASSIGNMENT_RULE: string;
  ASSIGNMENT_RULES: string;
  AUDIENCE: string;
  AURA_DEFINITION_BUNDLE: string;
  AUTH_PROVIDER: string;
  AUTORESPONSE_RULE: string;
  AUTORESPONSE_RULES: string;
  BATCH_CALC_JOB_DEFINITION: string;
  BATCH_PROCESS_JOB_DEFINITION: string;
  BLACKLISTED_CONSUMER: string;
  BOT: string;
  BOT_VERSION: string;
  BRANDING_SET: string;
  BRIEFCASE_DEFINITION: string;
  BUSINESS_PROCESS: string;
  BUSINESS_PROCESS_GROUP: string;
  CALL_COACHING_MEDIA_PROVIDER: string;
  CAMPAIGN_INFLUENCE_MODEL: string;
  CARE_PROVIDER_SEARCH_CONFIG: string;
  CARE_SYSTEM_FIELD_MAPPING: string;
  CASE_SUBJECT_PARTICLE: string;
  CERTIFICATE: string;
  CHATTER_EXTENSION: string;
  CLEAN_DATA_SERVICE: string;
  CMS_CONNECT_SOURCE: string;
  COMMUNITY: string;
  COMMUNITY_TEMPLATE_DEFINITION: string;
  COMMUNITY_THEME_DEFINITION: string;
  COMPACT_LAYOUT: string;
  CONNECTED_APP: string;
  CONTENT_ASSET: string;
  CORS_WHITELIST_ORIGIN: string;
  CSP_TRUSTED_SITE: string;
  CUSTOM_APPLICATION: string;
  CUSTOM_APP_COMPONENT: string;
  CUSTOM_FEED_FILTER: string;
  CUSTOM_FIELD: string;
  CUSTOM_HELP_MENU_SECTION: string;
  CUSTOM_LABEL: string;
  CUSTOM_LABELS: string;
  CUSTOM_METADATA: string;
  CUSTOM_NOTIFICATION_TYPE: string;
  CUSTOM_OBJECT: string;
  CUSTOM_OBJECT_TRANSLATIONS: string;
  CUSTOM_PAGE_WEB_LINK: string;
  CUSTOM_PERMISSION: string;
  CUSTOM_SITE: string;
  CUSTOM_TAB: string;
  DASHBOARD: string;
  DATA_CATEGORY_GROUP: string;
  DATA_PACKAGE_KIT_OBJECT: string;
  DATA_PACKAGE_KIT_DEFINITION: string;
  DATA_SOURCE: string;
  DATA_SOURCE_OBJECT: string;
  DATA_STREAM_DEFINITION: string;
  DECISION_TABLE: string;
  DECISION_TABLE_DATASET_LINK: string;
  DELEGATE_GROUP: string;
  DISCOVERY_AI_MODEL: string;
  DISCOVERY_GOAL: string;
  DOCUMENT: string;
  DUPLICATE_RULE: string;
  ECLAIR_GEO_DATA: string;
  EMAIL_SERVICES_FUNCTION: string;
  EMAIL_TEMPLATE: string;
  EMBEDDED_SERVICE_BRANDING: string;
  EMBEDDED_SERVICE_CONFIG: string;
  EMBEDDED_SERVICE_FIELD_SERVICE: string;
  EMBEDDED_SERVICE_FLOW_CONFIG: string;
  EMBEDDED_SERVICE_LIVE_AGENT: string;
  EMBEDDED_SERVICE_MENU_SETTINGS: string;
  ENTITLEMENT_PROCESS: string;
  ENTITLEMENT_TEMPLATE: string;
  EXTERNAL_AI_MODEL: string;
  ESCALATION_RULE: string;
  ESCALATION_RULES: string;
  EVENT_DELIVERY: string;
  EVENT_SUBSCRIPTION: string;
  EXPERIENCE_BUNDLE: string;
  EXTERNAL_DATA_CONNECTOR: string;
  EXTERNAL_DATA_SOURCE: string;
  EXTERNAL_SERVICE_REGISTRATION: string;
  FEATURE_PARAMETER_BOOLEAN: string;
  FEATURE_PARAMETER_DATE: string;
  FEATURE_PARAMETER_INTEGER: string;
  FIELD_RESTRICTION_RULE: string;
  FIELD_SET: string;
  FIELD_SRC_TRGT_RELATIONSHIP: string;
  FLEXI_PAGE: string;
  FLOW: string;
  FLOW_CATEGORY: string;
  FLOW_DEFINITION: string;
  FOLDER: string;
  FORECASTING_SOURCE_DEFFINITION: string;
  FORECASTING_TYPE: string;
  FORECASTING_TYPE_SOURCE: string;
  FUNCTION_REFERENCE: string;
  GATEWAY_PROVIDER_PAYMENT_METHOD_TYPE: string;
  GLOBAL_PICKLIST: string;
  GLOBAL_VALUE_SET: string;
  GLOBAL_VALUE_SET_TRANSLATION: string;
  GROUP: string;
  HISTORY_RETENTION_POLICY: string;
  HOME_COMPONENT: string;
  HOME_PAGE_LAYOUT: string;
  INBOUND_CERTIFICATE: string;
  INBOUND_NETWORK_CONNECTION: string;
  INDEX: string;
  INSTALLED_PACKAGE: string;
  IP_ADDRESS_RANGE: string;
  KEYWORD_LIST: string;
  LAYOUT: string;
  LETTERHEAD: string;
  LIGHTNING_BOLT: string;
  LIGHTNING_COMPONENT_BUNDLE: string;
  LIGHTNING_EXPERIENCE_THEME: string;
  LIGHTNING_MESSAGE_CHANNEL: string;
  LIGHTNING_ONBOARDING_CONFIG: string;
  LISTVIEW: string;
  LIVE_CHAT_AGENT_CONFIG: string;
  LIVE_CHAT_BUTTON: string;
  LIVE_CHAT_DEPLOYMENT: string;
  LIVE_CHAT_SENSITIVE_DATA_RULE: string;
  MANAGED_CONTENT_TYPE: string;
  MANAGED_TOPICS: string;
  MATCHING_RULE: string;
  MATCHING_RULES: string;
  MILESTONE_TYPE: string;
  ML_PREDICTION_DEFINITION: string;
  ML_DATA_DEFINITION: string;
  ML_DOMAIN: string;
  MKT_CALC_INSIGHT_OBJECT_DEF: string;
  MKT_DATA_TRAN_OBJECT: string;
  MOBILE_APPLICATION_DETAIL: string;
  MODERATION_RULE: string;
  MUTING_PERMISSION_SET: string;
  MY_DOMAIN_DISCOVERABLE_LOGIN: string;
  NAMED_CREDENTIAL: string;
  NAMED_FILTER: string;
  NAVIGATION_MENU: string;
  NETWORK: string;
  NETWORK_BRANDING: string;
  NOTIFICATION_TYPE_CONFIG: string;
  OAUTH_CUSTOM_SCOPE: string;
  OBJECT_SOURCE_TARGET_MAP: string;
  OCR_SAMPLE_DOCUMENT: string;
  OCR_TEMPLATE: string;
  OUTBOUND_NETWORK_CONNECTION: string;
  PACKAGE: string;
  PATH_ASSISTANT: string;
  PAYMENT_GATEWAY_PROVIDER: string;
  PERMISSION_SET: string;
  PERMISSION_SET_GROUP: string;
  PLATFORM_CACHE_PARTITION: string;
  PLATFORM_EVENT_CHANNEL: string;
  PLATFORM_EVENT_CHANNEL_MEMBER: string;
  PLATFORM_EVENT_SUBSCRIBER_CONFIG: string;
  PORTAL: string;
  POST_TEMPLATE: string;
  PRESENCE_DECLINE_REASON: string;
  PRESENCE_USER_CONFIG: string;
  PROFILE: string;
  PROFILE_PASSWORD_POLICY: string;
  PROFILE_SEARCH_LAYOUTS: string;
  PROFILE_SESSION_SETTING: string;
  PROMPT: string;
  QUEUE: string;
  QUEUE_ROUTING_CONFIG: string;
  QUICK_ACTION: string;
  RECOMMENDATION_STRATEGY: string;
  RECORD_ACTION_DEPLOYMENT: string;
  RECORD_TYPE: string;
  REDIRECT_WHITELIST_URL: string;
  REMOTE_SITE_SETTING: string;
  REPORT: string;
  REPORT_TYPE: string;
  ROLE: string;
  SALES_WORK_QUEUE_SETTINGS: string;
  SAML_SSO_CONFIG: string;
  S_CONTROL: string;
  SEARCH_LAYOUTS: string;
  SERVICE_AI_SETUP_DEFINITION: string;
  SERVICE_AI_SETUP_FIELD: string;
  SERVICE_CHANNEL: string;
  SERVICE_PRESENCE_STATUS: string;
  SHARED_TO: string;
  SHARING_REASON: string;
  SHARING_RECALCULATION: string;
  SHARING_RULES: string;
  SHARING_OWNER_RULE: string;
  SHARING_CRITERIA_RULE: string;
  SHARING_TERRITORY_RULE: string;
  SHARING_GUEST_RULE: string;
  SHARING_SET: string;
  SITE_DOT_COM: string;
  SKILL: string;
  STANDARD_VALUE_SET: string;
  STANDARD_VALUE_SET_TRANSLATION: string;
  STATIC_RESOURCE: string;
  SYNONYM_DICTIONARY: string;
  TERRITORY: string;
  TERRITORY_2: string;
  TERRITORY_2_MODEL: string;
  TERRITORY_2_RULE: string;
  TERRITORY_2_TYPE: string;
  TIME_SHEET_TEMPLATE: string;
  TOPICS_FOR_OBJECT: string;
  TRANSACTION_SECURITY_POLICY: string;
  TRANSLATIONS: string;
  USER_AUTH_CERTIFICATE: string;
  USER_CRITERIA: string;
  USER_PROVISIONING_CONFIG: string;
  VALIDATION_RULE: string;
  WAVE_APPLICATION: string;
  WAVE_DASHBOARD: string;
  WAVE_DATA_FLOW: string;
  WAVE_DATASET: string;
  WAVE_LENS: string;
  WAVE_RECIPE: string;
  WAVE_TEMPLATE_BUNDLE: string;
  WAVE_XMD: string;
  WEBLINK: string;
  WEB_STORE_TEMPLATE: string;
  WORKFLOW: string;
  WORKFLOW_ALERT: string;
  WORKFLOW_FIELD_UPDATE: string;
  WORKFLOW_RULE: string;
  WORKFLOW_TASK: string;
  WORKFLOW_SEND: string;
  WORKFLOW_OUTBOUND_MESSAGE: string;
  WORKFLOW_KNOWLEDGE_PUBLISH: string;
  WORK_SKILL_ROUTING: string;
};