module.exports = {
    PREPARE: 'preapre',
    CREATE_PROJECT: 'createProject',
    RETRIEVE: 'retrieve',
    PROCESS: 'process',
    CLEANING: 'cleaning',
    LOADING_LOCAL: 'loadingLocal',
    LOADING_ORG: 'loadingOrg',
    COPY_DATA: 'copyData',
    COPY_FILE: 'copyFile',
    COMPRESS_FILE: 'compressFile',
    BEFORE_DOWNLOAD: 'beforeDownload',
    AFTER_DOWNLOAD: 'afterDownload',
    START_TYPE: 'startType',
    START_OBJECT: 'startObject',
    START_ITEM: 'startItem',
    END_TYPE: 'endType',
    END_OBJECT: 'endObject',
    END_ITEM: 'endItem',
    START_ERROR: 'startError',
    END_ERROR: 'endError',
    FILE_ERROR: 'fileError',
};